// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCPC3gmn3WKwoR4ux19VA6Tb6c11h0SM4',
    appId: '1:761892859360:web:98f5ded85112cbce5a0f85',
    messagingSenderId: '761892859360',
    projectId: 'atm-helwan',
    authDomain: 'atm-helwan.firebaseapp.com',
    storageBucket: 'atm-helwan.firebasestorage.app',
    measurementId: 'G-2DWVBMVFNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQ__Ay-6VYpvS-hJdJtX_g6XnG2LlstE',
    appId: '1:761892859360:android:ea7b38929aa91f9a5a0f85',
    messagingSenderId: '761892859360',
    projectId: 'atm-helwan',
    storageBucket: 'atm-helwan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKjOgFhc5jjIgfTHINa3GEjA_uI7glds',
    appId: '1:761892859360:ios:588c449e15fa1f755a0f85',
    messagingSenderId: '761892859360',
    projectId: 'atm-helwan',
    storageBucket: 'atm-helwan.firebasestorage.app',
    iosBundleId: 'com.example.atmHelwan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByKjOgFhc5jjIgfTHINa3GEjA_uI7glds',
    appId: '1:761892859360:ios:588c449e15fa1f755a0f85',
    messagingSenderId: '761892859360',
    projectId: 'atm-helwan',
    storageBucket: 'atm-helwan.firebasestorage.app',
    iosBundleId: 'com.example.atmHelwan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCPC3gmn3WKwoR4ux19VA6Tb6c11h0SM4',
    appId: '1:761892859360:web:b180c345db61885b5a0f85',
    messagingSenderId: '761892859360',
    projectId: 'atm-helwan',
    authDomain: 'atm-helwan.firebaseapp.com',
    storageBucket: 'atm-helwan.firebasestorage.app',
    measurementId: 'G-LNPC0TYS0L',
  );
}
